### PR TITLE
fix #36 responsiveness

### LINKED ISSUE #36: homepage responsiveness
The responsiveness of the homepage needs to be fixed. For large devices, it is fine, but for smaller devices, the bootstrap doesn't work out. Some of the components in the homepage needs to be removed while others need to be enlarged to fill up the empty space. This means that the <Col> width of sm and xs should be 12 or hidden depending on which component it is.

### PR DESCRIPTION
**Pull request by guilhermemarconi**
It's normal to no not load nothing but the header, menu and the _loading_ on the pages?
Anyway, I fixed the responsiveness on these components, and in the logo, that looks for the page width on load and set its `font-size`. I would do something better, but the `react-jss` seems to not have media query support.

Hope it helps :)

### CODE REVIEW

**Comment by NicholasLYang** [comment]
Hi @guilhermemarconi! Media queries are supported by react-jss. Here's [an example](https://github.com/NicholasLYang/NicholasLYang.github.io/blob/master/src/js/modules/core/components/AboutPage.js) from my portfolio.

**Comment by guilhermemarconi** [comment]
Nice! I'll fix that :)

**Comment by guilhermemarconi** [comment]
@NicholasLYang take a look, now :)

**Comment by NicholasLYang** [comment]
Great! Merged. Also the loading thing is just a temp. If you run the [server](https://github.com/stuyspec/stuy-spec-api) then it loads the relevant data. (Of course after you create the db, seed, blah blah blah. We've been too lazy to implement docker haha)

**Comment by guilhermemarconi** [comment]
I see... so, don't forget to show me when it's completed!

**Pull request merged**
